# fly.toml app configuration file generated for june-portfolio-dev on 2023-06-25T07:48:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "june-portfolio-dev"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
